// <auto-generated />
namespace prueba1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class cambiandonotacionesyrelacionandotablas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambiandonotacionesyrelacionandotablas));
        
        string IMigrationMetadata.Id
        {
            get { return "202111151647305_cambiando notaciones y relacionando tablas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
